import { Metadata } from "next";
import { Toaster } from "react-hot-toast";
const keys = [
  "împrumut",
  "datorie",
  "creditare",
  "îndatorare",
  "dobîndă",
  "credit card",
  "cheltuieli",
  "rambursare anticipată",
  "Credit Rapid",
  "Credit doar cu buletinul",
  "Credite fara gaj",
  "Credite in Chisinau",
  "Credite in Moldova",
  "Credit Nebancar",
  "Credit bancar",
  "Credit fără adeverință salariu",
  "FINANȚARE",
  "numerar",
  "gaj",
  "online",
  "rate",
  "bani",
  "Credite247.md",
  "OkCredit",
  "kreddy",
  "Rapid finance",
  "creditcasa",
  "expresbani",
  "credit bun",
  "leasing",
  "doctorcredit",
  "credit7",
  "Forza Credit",
  "smart credit",
  "easy credit",
  "bani pe datorie",
  "iute credit",
  "sebo",
  "Personal Credit",
  "Invest Credit",
  "Dino Credit",
  "Super Credit",
  "Direct Credit",
  "credit simplu",
  "simplu credit",
  "bani credit",
  "credit urgent",
  "împrumut invest",
  "refinanțare",
  "refinantare",
  "reinvestire",
  "B&B credit",
  "salariu",
  "cadou",
  "rezerva",
  "consum",
  "procent",
  "garant",
  "fidejusor",
  "incaso",
  "colectare",
  "asociatie de imprumut",
  "DaCredit",
  "Credit365",
  "OK Credit",
  "Forza credit",
  "sebo credit",
  "Scoring Creditar",
  "vcredit",
  "microinvest",
  "credit rapid",
  "DAE",
  "Moldova Agoindbank",
  "Card de credit",
  "Victoriabank",
  "Mobiasbank",
  "Moldinconbank",
  "Ciki Ciki tu",
  "Anticolect",
  "Colectare creante",
  "Creanțe, Ipotecă",
  "pay",
  "online pay",
  "bpay",
  "oplatamd",
  "qiwi",
  "Eximbank",
  "Energbank",
  "Calculator de credit",
  "credit prime",
  "credit online pe card",
  "cardcredit",
  "amigocredit",
  "credit negajat",
  "credit neoficial",
  "licentă de credit",
  "OCN",
  "organizație de creditare nebancară",
  "credit moldova",
  "prime credit",
  "credit online",
  "ecredit",
  "credit fara",
  "999 credit",
  "credit euro",
  "credit orange",
  "terra credit",
  "credit",
  "creditplus",
  "credit cu gaj",
  "money credit",
  "credit comod",
  "iphone credit",
  "victoria credit",
  "credit client",
  "credit auto",
  "credit bank",
  "accept credit",
  "smart credit",
  "sms credit",
  "credit v",
  "fincombank",
  "bbcredit",
  "credit me",
  "my credit",
  "lombard",
  "blago",
  "cashpoint",
  "amanet",
  "amanet.md",
  "tehnolombard",
  "incaso",
  "Pfbcolection",
  "finantare",
  "primecapital",
  "ofertă creditară",
  "îmrumut rapid",
  "imprumuturi",
  "займ",
  "займу место",
  "займы молдова",
  "договор займа",
  "займы онлайн",
  "взять займ",
  "займ без",
  "частный займ",
  "кредит займ",
  "лайм займ",
  "деньги займ",
  "предоставление займов",
  "займ срочно",
  "кредитный займ",
  "займы без карты",
  "займ под расписку",
  "финансовый займ",
  "займ кабинет",
  "займ физическому",
  "срок займа",
  "срочный деньги",
  "деньги долг",
  "под залог",
  "кредит под кредит",
  "кредит под залог",
  "взять кредит",
  "микрозайм онлайн",
  "срочный долг",
  "деньги зарплата",
  "купить в кредит",
  "банки кредиты",
  "кредит в молдове",
  "кредит без",
  "кредит онлайн",
  "где кредит",
  "кредит без справок",
  "получить кредит",
  "кредит наличными",
  "кредит мд",
  "где взять кредит",
  "кредит без дохода",
  "кредит под проценты",
  "кредитный кредит",
  "данные кредитам",
  "юте кредит",
  "банки под кредит",
  "дам кредит",
  "даю кредит",
  "финансовый кредит",
  "телефон в кредит",
  "финансовый кредит",
  "кредитный калькулятор",
  "кредитная карта",
  "кредитная история",
  "доход справка",
  "банк заявка",
  "себо",
  "изи кредит",
  "процент",
  "кредит безработным",
  "автофинансы",
  "Дельтакредит",
  "Рефинансирование",
  "кредитный скоринг",
  "Тарифная ставка",
  "împrumut personal",
  "împrumut rapid online",
  "credite pentru pensionari",
  "soluții financiare",
  "credit pentru studenți",
  "împrumut pentru afaceri",
  "credite pe termen lung",
  "credite pe termen scurt",
  "servicii bancare",
  "credite cu dobândă mică",
  "credit pentru renovare",
  "imprumut pentru casă",
  "credit pentru autoturism",
  "împrumut pentru educație",
  "credit fără verificare birou de credit",
  "finanțare pe termen lung",
  "credite pentru IMM-uri",
  "credit pentru startup-uri",
  "împrumuturi rapide fără garanție",
  "plată online sigură",
  "aprovizionare rapidă",
  "credit flexibile",
  "bani împrumut urgent",
  "carduri de credit instant",
  "servicii de refinanțare",
  "credite bancare avantajoase",
  "calculator online de împrumut",
  "estimează rata lunară",
  "programe de credite pentru tineri",
  "credite accesibile",
  "dobândă fixă",
  "dobândă variabilă",
  "plăți flexibile",
  "imprumuturi online rapide",
  "platforme de creditare",
  "credite 100% online",
  "consolidare datorii",
  "refinanțare credite bancare",
  "împrumuturi fără verificare istoric credit",
  "credite fără garanție imobiliară",
  "carduri de credit cu beneficii",
  "împrumut rapid fără acte",
  "împrumuturi fără dobândă",
  "credit pentru călătorii",
  "credite pentru vacanțe",
  "credite pentru achiziții de produse",
  "credit pe loc",
  "împrumut rapid în 24h",
  "credite în rate fixe",
  "împrumuturi fără comision",
  "credit instant",
  "transfer rapid bani",
  "credite pentru consolidarea datoriei",
  "finanțare pentru renovări",
  "microfinanțare",
  "împrumuturi pentru orice scop",
  "închiriere echipamente financiare",
  "finanțare directă",
  "finanțare urgentă",
  "credit pentru achiziții personale",
  "credite cu aprobare rapidă",
  "soluții financiare rapide",
  "refinanțare personalizată",
  "credit prin aplicație mobilă",
  "credite fără activitate economică",
  "credit de consum",
  "finanțare pentru proiecte",
  "bani împrumut fără acte",
];

export const metadata: Metadata = {
  metadataBase: new URL("https://bbcredit.md/"),
  title: "B&B Credit - Credite pentru toți până la 40.000 lei",
  description:
    "Obține cele mai bune soluții financiare cu B&B Credit. Rapid, sigur și orientat către client.",
  keywords: keys,
  robots: "index, follow",
  openGraph: {
    title: "B&B Credit - Credite pentru toți până la 40.000 lei",
    description:
      "Obține cele mai bune soluții financiare cu B&B Credit. Rapid, sigur și orientat către client.",
    url: "https://bbcredit.md",
    siteName: "B&B Credit",
    images: [
      {
        url: "/bb_logo.jpg",
        width: 1920,
        height: 1080,
        alt: "B&B Credit - Credite rapide și sigure",
      },
    ],
    type: "website",
  },
};
export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      {children}
      <Toaster />
    </main>
  );
}
